package com.test.platform.hawkeye.domain.general;

public class AutoCaseInterface {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column he_auto_case_interface.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column he_auto_case_interface.project_id
     *
     * @mbg.generated
     */
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column he_auto_case_interface.interface_id
     *
     * @mbg.generated
     */
    private Integer interfaceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column he_auto_case_interface.case_id
     *
     * @mbg.generated
     */
    private Integer caseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column he_auto_case_interface.is_delete
     *
     * @mbg.generated
     */
    private Integer isDelete = 0;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column he_auto_case_interface.id
     *
     * @return the value of he_auto_case_interface.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column he_auto_case_interface.id
     *
     * @param id the value for he_auto_case_interface.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column he_auto_case_interface.project_id
     *
     * @return the value of he_auto_case_interface.project_id
     *
     * @mbg.generated
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column he_auto_case_interface.project_id
     *
     * @param projectId the value for he_auto_case_interface.project_id
     *
     * @mbg.generated
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column he_auto_case_interface.interface_id
     *
     * @return the value of he_auto_case_interface.interface_id
     *
     * @mbg.generated
     */
    public Integer getInterfaceId() {
        return interfaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column he_auto_case_interface.interface_id
     *
     * @param interfaceId the value for he_auto_case_interface.interface_id
     *
     * @mbg.generated
     */
    public void setInterfaceId(Integer interfaceId) {
        this.interfaceId = interfaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column he_auto_case_interface.case_id
     *
     * @return the value of he_auto_case_interface.case_id
     *
     * @mbg.generated
     */
    public Integer getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column he_auto_case_interface.case_id
     *
     * @param caseId the value for he_auto_case_interface.case_id
     *
     * @mbg.generated
     */
    public void setCaseId(Integer caseId) {
        this.caseId = caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column he_auto_case_interface.is_delete
     *
     * @return the value of he_auto_case_interface.is_delete
     *
     * @mbg.generated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column he_auto_case_interface.is_delete
     *
     * @param isDelete the value for he_auto_case_interface.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}