package com.test.platform.hawkeye.domain.general;

import java.util.Date;

public class AutoCase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column he_auto_case.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column he_auto_case.cid
     *
     * @mbg.generated
     */
    private String cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column he_auto_case.project_id
     *
     * @mbg.generated
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column he_auto_case.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column he_auto_case.path
     *
     * @mbg.generated
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column he_auto_case.level
     *
     * @mbg.generated
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column he_auto_case.author
     *
     * @mbg.generated
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column he_auto_case.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column he_auto_case.case_grade
     *
     * @mbg.generated
     */
    private Integer caseGrade = 80;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column he_auto_case.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column he_auto_case.is_delete
     *
     * @mbg.generated
     */
    private Integer isDelete = 0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column he_auto_case.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column he_auto_case.id
     *
     * @return the value of he_auto_case.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column he_auto_case.id
     *
     * @param id the value for he_auto_case.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column he_auto_case.cid
     *
     * @return the value of he_auto_case.cid
     * @mbg.generated
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column he_auto_case.cid
     *
     * @param cid the value for he_auto_case.cid
     * @mbg.generated
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column he_auto_case.project_id
     *
     * @return the value of he_auto_case.project_id
     * @mbg.generated
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column he_auto_case.project_id
     *
     * @param projectId the value for he_auto_case.project_id
     * @mbg.generated
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column he_auto_case.name
     *
     * @return the value of he_auto_case.name
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column he_auto_case.name
     *
     * @param name the value for he_auto_case.name
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column he_auto_case.path
     *
     * @return the value of he_auto_case.path
     * @mbg.generated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column he_auto_case.path
     *
     * @param path the value for he_auto_case.path
     * @mbg.generated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column he_auto_case.level
     *
     * @return the value of he_auto_case.level
     * @mbg.generated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column he_auto_case.level
     *
     * @param level the value for he_auto_case.level
     * @mbg.generated
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column he_auto_case.author
     *
     * @return the value of he_auto_case.author
     * @mbg.generated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column he_auto_case.author
     *
     * @param author the value for he_auto_case.author
     * @mbg.generated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column he_auto_case.description
     *
     * @return the value of he_auto_case.description
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column he_auto_case.description
     *
     * @param description the value for he_auto_case.description
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column he_auto_case.case_grade
     *
     * @return the value of he_auto_case.case_grade
     * @mbg.generated
     */
    public Integer getCaseGrade() {
        return caseGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column he_auto_case.case_grade
     *
     * @param caseGrade the value for he_auto_case.case_grade
     * @mbg.generated
     */
    public void setCaseGrade(Integer caseGrade) {
        this.caseGrade = caseGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column he_auto_case.create_time
     *
     * @return the value of he_auto_case.create_time
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column he_auto_case.create_time
     *
     * @param createTime the value for he_auto_case.create_time
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column he_auto_case.is_delete
     *
     * @return the value of he_auto_case.is_delete
     * @mbg.generated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column he_auto_case.is_delete
     *
     * @param isDelete the value for he_auto_case.is_delete
     * @mbg.generated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column he_auto_case.content
     *
     * @return the value of he_auto_case.content
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column he_auto_case.content
     *
     * @param content the value for he_auto_case.content
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }


    @Override
    public String toString() {
        return "AutoCase{" +
                "id=" + id +
                ", cid='" + cid + '\'' +
                ", projectId=" + projectId +
                ", name='" + name + '\'' +
                ", path='" + path + '\'' +
                ", level='" + level + '\'' +
                ", author='" + author + '\'' +
                ", description='" + description + '\'' +
                ", caseGrade=" + caseGrade +
                ", createTime=" + createTime +
                ", isDelete=" + isDelete +
                ", content='" + content + '\'' +
                '}';
    }
}