package com.test.platform.hawkeye.domain.general;

import java.util.Date;

public class Interface {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column he_interface.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column he_interface.project_id
     *
     * @mbg.generated
     */
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column he_interface.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column he_interface.path
     *
     * @mbg.generated
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column he_interface.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column he_interface.is_auto
     *
     * @mbg.generated
     */
    private Integer isAuto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column he_interface.ceeate_time
     *
     * @mbg.generated
     */
    private Date ceeateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column he_interface.is_delete
     *
     * @mbg.generated
     */
    private Byte isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column he_interface.request_type
     *
     * @mbg.generated
     */
    private Integer requestType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column he_interface.id
     *
     * @return the value of he_interface.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column he_interface.id
     *
     * @param id the value for he_interface.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column he_interface.project_id
     *
     * @return the value of he_interface.project_id
     *
     * @mbg.generated
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column he_interface.project_id
     *
     * @param projectId the value for he_interface.project_id
     *
     * @mbg.generated
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column he_interface.name
     *
     * @return the value of he_interface.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column he_interface.name
     *
     * @param name the value for he_interface.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column he_interface.path
     *
     * @return the value of he_interface.path
     *
     * @mbg.generated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column he_interface.path
     *
     * @param path the value for he_interface.path
     *
     * @mbg.generated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column he_interface.type
     *
     * @return the value of he_interface.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column he_interface.type
     *
     * @param type the value for he_interface.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column he_interface.is_auto
     *
     * @return the value of he_interface.is_auto
     *
     * @mbg.generated
     */
    public Integer getIsAuto() {
        return isAuto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column he_interface.is_auto
     *
     * @param isAuto the value for he_interface.is_auto
     *
     * @mbg.generated
     */
    public void setIsAuto(Integer isAuto) {
        this.isAuto = isAuto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column he_interface.ceeate_time
     *
     * @return the value of he_interface.ceeate_time
     *
     * @mbg.generated
     */
    public Date getCeeateTime() {
        return ceeateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column he_interface.ceeate_time
     *
     * @param ceeateTime the value for he_interface.ceeate_time
     *
     * @mbg.generated
     */
    public void setCeeateTime(Date ceeateTime) {
        this.ceeateTime = ceeateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column he_interface.is_delete
     *
     * @return the value of he_interface.is_delete
     *
     * @mbg.generated
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column he_interface.is_delete
     *
     * @param isDelete the value for he_interface.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column he_interface.request_type
     *
     * @return the value of he_interface.request_type
     *
     * @mbg.generated
     */
    public Integer getRequestType() {
        return requestType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column he_interface.request_type
     *
     * @param requestType the value for he_interface.request_type
     *
     * @mbg.generated
     */
    public void setRequestType(Integer requestType) {
        this.requestType = requestType;
    }
}