package com.test.platform.hawkeye.dao;

import com.test.platform.hawkeye.domain.general.AutoCaseInterface;
import com.test.platform.hawkeye.domain.general.AutoCaseInterfaceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;


@Repository
public interface AutoCaseInterfaceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table he_auto_case_interface
     *
     * @mbg.generated
     */
    long countByExample(AutoCaseInterfaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table he_auto_case_interface
     *
     * @mbg.generated
     */
    int deleteByExample(AutoCaseInterfaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table he_auto_case_interface
     *
     * @mbg.generated
     */
    int insert(AutoCaseInterface record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table he_auto_case_interface
     *
     * @mbg.generated
     */
    int insertSelective(AutoCaseInterface record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table he_auto_case_interface
     *
     * @mbg.generated
     */
    List<AutoCaseInterface> selectByExample(AutoCaseInterfaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table he_auto_case_interface
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AutoCaseInterface record, @Param("example") AutoCaseInterfaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table he_auto_case_interface
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AutoCaseInterface record, @Param("example") AutoCaseInterfaceExample example);
}