package com.test.platform.hawkeye.dao;

import com.test.platform.hawkeye.domain.general.AutoCase;
import com.test.platform.hawkeye.domain.general.AutoCaseExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;


@Repository
public interface AutoCaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table he_auto_case
     *
     * @mbg.generated
     */
    long countByExample(AutoCaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table he_auto_case
     *
     * @mbg.generated
     */
    int deleteByExample(AutoCaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table he_auto_case
     *
     * @mbg.generated
     */
    int insert(AutoCase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table he_auto_case
     *
     * @mbg.generated
     */
    int insertSelective(AutoCase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table he_auto_case
     *
     * @mbg.generated
     */
    List<AutoCase> selectByExampleWithBLOBs(AutoCaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table he_auto_case
     *
     * @mbg.generated
     */
    List<AutoCase> selectByExample(AutoCaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table he_auto_case
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AutoCase record, @Param("example") AutoCaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table he_auto_case
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") AutoCase record, @Param("example") AutoCaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table he_auto_case
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AutoCase record, @Param("example") AutoCaseExample example);
}