package com.test.platform.hawkeye.dao;

import com.test.platform.hawkeye.domain.general.Interface;
import com.test.platform.hawkeye.domain.general.InterfaceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InterfaceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table he_interface
     *
     * @mbg.generated
     */
    long countByExample(InterfaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table he_interface
     *
     * @mbg.generated
     */
    int deleteByExample(InterfaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table he_interface
     *
     * @mbg.generated
     */
    int insert(Interface record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table he_interface
     *
     * @mbg.generated
     */
    int insertSelective(Interface record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table he_interface
     *
     * @mbg.generated
     */
    List<Interface> selectByExample(InterfaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table he_interface
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Interface record, @Param("example") InterfaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table he_interface
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Interface record, @Param("example") InterfaceExample example);
}