package com.test.platform.hawkeye.dao;

import com.test.platform.hawkeye.domain.general.ProjectAnalysis;
import com.test.platform.hawkeye.domain.general.ProjectAnalysisExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;


@Repository
public interface ProjectAnalysisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table he_project_analysis
     *
     * @mbg.generated
     */
    long countByExample(ProjectAnalysisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table he_project_analysis
     *
     * @mbg.generated
     */
    int deleteByExample(ProjectAnalysisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table he_project_analysis
     *
     * @mbg.generated
     */
    int insert(ProjectAnalysis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table he_project_analysis
     *
     * @mbg.generated
     */
    int insertSelective(ProjectAnalysis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table he_project_analysis
     *
     * @mbg.generated
     */
    List<ProjectAnalysis> selectByExampleWithBLOBs(ProjectAnalysisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table he_project_analysis
     *
     * @mbg.generated
     */
    List<ProjectAnalysis> selectByExample(ProjectAnalysisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table he_project_analysis
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ProjectAnalysis record, @Param("example") ProjectAnalysisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table he_project_analysis
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") ProjectAnalysis record, @Param("example") ProjectAnalysisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table he_project_analysis
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ProjectAnalysis record, @Param("example") ProjectAnalysisExample example);
}